### ISSUE TITLE
Can't test solution for task 09

### ISSUE THREAD

**Issue by SavinovJr** [flutter/udacity-course#134]
Hi,

I can't test solution for task 09. Got the error:

`Syncing files to device iPhone X...
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
'file:///Users/antonsavinov/Documents/My%20Documents/TestProjects/flutterUdacity/task_09_real_units/lib/unit.dart': error: line 25 pos 16: lib/unit.dart:25:16: Error: Can't access 'this' in a field initializer to read 'name'.
        assert(name != null),
               ^^^^
        assert(name != null),
               ^
#0      _CategoryRouteState._retrieveLocalCategories.<anonymous closure>.<anonymous closure> (file:///Users/antonsavinov/Documents/My%20Documents/TestProjects/flutterUdacity/task_09_real_units/lib/category_route.dart:103:21)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#2      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#3      _CategoryRouteState._retrieveLocalCategories.<anonymous closure> (file:///Users/antonsavinov/Documents/My%20Documents/TestProjects/flutterUdacity/task_09_real_units/lib/category_route.dart:104:10)
#4      Iterable.forEach (dart:core/iterable.dart:277:30)
#5 <…>`

Looks like some issues are in this piece of code:
`var index = 0;
    jsondata.keys.forEach((key) {
      dynamic someData = jsondata[key];
      final List<Unit> units = someData.map((data) {
        return Unit.fromJson(data);
      }).toList();

      var category = Category(
        name: key,
        units: units,
        color: _baseColors[index],
        iconLocation: Icons.cake,
      );
      setState(() {
        if (index == 0) {
          _defaultCategory = category;
        }
        _categories.add(category);
      });
      index += 1;
    });`

But I investigated solution from Udacity course and got the same error. So could someone look at it, please?

**Comment by maryx** [comment]
Hi @SavinovJr,
What happens when you try running this on an Android device/emulator? I just tried it on both an Android and iPhone X (Simulator) without issues.
What version of Flutter do you have? Maybe it's out of date. What does `flutter doctor` output?

**Comment by SavinovJr** [comment]
Hi @maryx , `flutter doctor` output is the next

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by maryx** [comment]
Hi @SavinovJr,
It seems like we have to now put asserts before assignments, with the latest updates to Dart.
(See https://github.com/dart-lang/sdk/issues/30968)
Can you try changing the code to:
```
Unit.fromJson(Map jsonMap)
      : assert(jsonMap['name'] != null),
        assert(jsonMap['conversion'] != null),
        name = jsonMap['name'],
        conversion = jsonMap['conversion'].toDouble();
```
I'm going to test this out a bit later, but you can try it first!

**Comment by chalin** [comment]
> It seems like we have to now put asserts before assignments, with the latest updates to Dart.

I don't think so. I see no such constraint in the [language spec](https://github.com/dart-lang/sdk/blob/master/docs/language/dartLangSpec.tex), but I'll let @eernstg or @munificent confirm. (I just checked against Dart 2.1.0-dev.5.0 (VM), and asserts after assignments are ok.)

---

The source of the **problem** reported here seems to be the **attempted read of a field from within the initializer list**:

```
lib/unit.dart:25:16: Error: Can't access 'this' in a field initializer to read 'name'.
```

AFAIK, this has always been a constraint (for the Dart VM). @eernstg @mit-mit: Maybe the Flutter/Dart SDK has only recently been updated to match this behavior?

/cc @kwalrath

**Comment by horgag1** [comment]
Was having the problem as @SavinovJr. Putting the assets before the assignment works for me. All good!

**Comment by maryx** [comment]
@chalin thank you for clarifying the problem! I didn't fully understand the source of the issue. It does seem like a recent update.

**Comment by SavinovJr** [comment]
@maryx Hi. I've just checked this code. This approach works. Does it make sense update the course with this fix or should there be anything else?

**Comment by maryx** [comment]
Yep the course code needs to be updated. You can make a Pull Request against this repo's master branch (for each project in the courses directory, and the main app). Alternatively I can make one sometime later this week and add you as a reviewer.

**Comment by SavinovJr** [comment]
@maryx Hi. Can't make a Pull Request. Got the error:

`Pushing to https://github.com/flutter/udacity-course.git
remote: Permission to flutter/udacity-course.git denied to SavinovJr.
fatal: unable to access 'https://github.com/flutter/udacity-course.git/': The requested URL returned error: 403`

**Comment by maryx** [comment]
You should push to a branch in your own local fork of this repo, and then, from https://github.com/flutter/udacity-course/compare, choose to compare against forks, and select your branch, to make a pull request against this project.

**Comment by maryx** [comment]
LGTM! Thanks for your contribution!

**Comment by haikajymada** [comment]
> 
> 
> Hi @SavinovJr,
> It seems like we have to now put asserts before assignments, with the latest updates to Dart. I had been using an older version of Flutter, which is why I hadn't encountered the issue earlier.
> See [dart-lang/sdk#30968](https://github.com/dart-lang/sdk/issues/30968).
> 
> Can you try changing the code to:
> 
> ```
> Unit.fromJson(Map jsonMap)
>       : assert(jsonMap['name'] != null),
>         assert(jsonMap['conversion'] != null),
>         name = jsonMap['name'],
>         conversion = jsonMap['conversion'].toDouble();
> ```
> 
> I'll also make a PR which will resolve the issue.

This is the solution.
The current "unit.dart" file doesn't definitely work with Flutter 1.x
The version in the repository has to be updated quickly

**Comment by maryx** [comment]
@haikajymada What error are you getting currently?
In which coding exercise(s) are you getting the error?

**Comment by haikajymada** [comment]
> 
> 
> @haikajymada What error are you getting currently?
> In which coding exercise(s) are you getting the error?

in unit_converter/unit_converter, more exactly unit.dart file

**Comment by maryx** [comment]
Can you please:

- paste the logs from your error?

- do a `git log` to see what the most recent version of the code is?

- paste the output of `flutter doctor -v`

Thanks!
